title: Waves Theme
author:
  name: author
  email: email@email.me
description: >
  a theme for jekyll
github:
  username: user
  repo: user.github.io
permalink: /:categories/:title/

theme: minima

plugins: 
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: solarized

collections:
  documents:
    output: true
    
excerpt_separator: <!--more-->
